ALTER TABLE producers
    ADD COLUMN IF NOT EXISTS two_phase_commit BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE transactions
    ADD COLUMN IF NOT EXISTS two_phase_commit BOOLEAN NOT NULL DEFAULT FALSE;
