use rutomq_control::ControlError;

pub const NO_ERROR: i16 = 0;
pub const UNKNOWN_SERVER_ERROR: i16 = -1;
pub const OFFSET_OUT_OF_RANGE: i16 = 1;
pub const CORRUPT_MESSAGE: i16 = 2;
pub const UNKNOWN_TOPIC_OR_PARTITION: i16 = 3;
pub const NOT_LEADER_OR_FOLLOWER: i16 = 6;
pub const REQUEST_TIMED_OUT: i16 = 7;
pub const REPLICA_NOT_AVAILABLE: i16 = 9;
pub const MESSAGE_TOO_LARGE: i16 = 10;
pub const OFFSET_METADATA_TOO_LARGE: i16 = 12;
pub const INVALID_TOPIC_EXCEPTION: i16 = 17;
pub const NOT_ENOUGH_REPLICAS: i16 = 19;
pub const INVALID_REQUIRED_ACKS: i16 = 21;
pub const ILLEGAL_GENERATION: i16 = 22;
pub const INCONSISTENT_GROUP_PROTOCOL: i16 = 23;
pub const UNKNOWN_MEMBER_ID: i16 = 25;
pub const INVALID_SESSION_TIMEOUT: i16 = 26;
pub const REBALANCE_IN_PROGRESS: i16 = 27;
pub const TOPIC_AUTHORIZATION_FAILED: i16 = 29;
pub const GROUP_AUTHORIZATION_FAILED: i16 = 30;
pub const CLUSTER_AUTHORIZATION_FAILED: i16 = 31;
pub const INVALID_TIMESTAMP: i16 = 32;
pub const UNSUPPORTED_SASL_MECHANISM: i16 = 33;
pub const ILLEGAL_SASL_STATE: i16 = 34;
pub const UNSUPPORTED_VERSION: i16 = 35;
pub const TOPIC_ALREADY_EXISTS: i16 = 36;
pub const INVALID_PARTITIONS: i16 = 37;
pub const INVALID_REPLICATION_FACTOR: i16 = 38;
pub const INVALID_REPLICA_ASSIGNMENT: i16 = 39;
pub const INVALID_CONFIG: i16 = 40;
pub const INVALID_REQUEST: i16 = 42;
pub const COORDINATOR_NOT_AVAILABLE: i16 = 15;
pub const POLICY_VIOLATION: i16 = 44;
pub const UNSUPPORTED_COMPRESSION_TYPE: i16 = 76;
pub const OFFSET_NOT_AVAILABLE: i16 = 78;
pub const MEMBER_ID_REQUIRED: i16 = 79;
pub const GROUP_MAX_SIZE_REACHED: i16 = 81;
pub const FENCED_INSTANCE_ID: i16 = 82;
pub const OUT_OF_ORDER_SEQUENCE_NUMBER: i16 = 45;
pub const INVALID_PRODUCER_EPOCH: i16 = 47;
pub const INVALID_TXN_STATE: i16 = 48;
pub const INVALID_TRANSACTION_TIMEOUT: i16 = 50;
pub const TRANSACTION_COORDINATOR_FENCED: i16 = 52;
pub const TRANSACTIONAL_ID_AUTHORIZATION_FAILED: i16 = 53;
pub const SECURITY_DISABLED: i16 = 54;
pub const OPERATION_NOT_ATTEMPTED: i16 = 55;
pub const KAFKA_STORAGE_ERROR: i16 = 56;
pub const SASL_AUTHENTICATION_FAILED: i16 = 58;
pub const UNKNOWN_PRODUCER_ID: i16 = 59;
pub const DELEGATION_TOKEN_AUTH_DISABLED: i16 = 61;
pub const DELEGATION_TOKEN_NOT_FOUND: i16 = 62;
pub const DELEGATION_TOKEN_OWNER_MISMATCH: i16 = 63;
pub const DELEGATION_TOKEN_REQUEST_NOT_ALLOWED: i16 = 64;
pub const DELEGATION_TOKEN_AUTHORIZATION_FAILED: i16 = 65;
pub const DELEGATION_TOKEN_EXPIRED: i16 = 66;
pub const INVALID_PRINCIPAL_TYPE: i16 = 67;
pub const NON_EMPTY_GROUP: i16 = 68;
pub const FENCED_LEADER_EPOCH: i16 = 74;
pub const UNKNOWN_LEADER_EPOCH: i16 = 75;
pub const FETCH_SESSION_ID_NOT_FOUND: i16 = 70;
pub const INVALID_FETCH_SESSION_EPOCH: i16 = 71;
pub const ELECTION_NOT_NEEDED: i16 = 84;
pub const NO_REASSIGNMENT_IN_PROGRESS: i16 = 85;
pub const GROUP_SUBSCRIBED_TO_TOPIC: i16 = 86;
pub const INVALID_RECORD: i16 = 87;
pub const THROTTLING_QUOTA_EXCEEDED: i16 = 89;
pub const PRODUCER_FENCED: i16 = 90;
pub const RESOURCE_NOT_FOUND: i16 = 91;
pub const DUPLICATE_RESOURCE: i16 = 92;
pub const UNACCEPTABLE_CREDENTIAL: i16 = 93;
pub const INVALID_UPDATE_VERSION: i16 = 95;
pub const FEATURE_UPDATE_FAILED: i16 = 96;
pub const TRANSACTIONAL_ID_NOT_FOUND: i16 = 105;
pub const FETCH_SESSION_TOPIC_ID_ERROR: i16 = 106;
pub const UNKNOWN_TOPIC_ID: i16 = 100;
pub const GROUP_ID_NOT_FOUND: i16 = 69;
pub const FENCED_MEMBER_EPOCH: i16 = 110;
pub const UNRELEASED_INSTANCE_ID: i16 = 111;
pub const UNSUPPORTED_ASSIGNOR: i16 = 112;
pub const STALE_MEMBER_EPOCH: i16 = 113;
pub const MISMATCHED_ENDPOINT_TYPE: i16 = 114;
pub const UNSUPPORTED_ENDPOINT_TYPE: i16 = 115;
pub const UNKNOWN_SUBSCRIPTION_ID: i16 = 117;
pub const TELEMETRY_TOO_LARGE: i16 = 118;
pub const INVALID_RECORD_STATE: i16 = 121;
pub const SHARE_SESSION_NOT_FOUND: i16 = 122;
pub const INVALID_SHARE_SESSION_EPOCH: i16 = 123;
pub const FENCED_STATE_EPOCH: i16 = 124;
pub const INVALID_REGULAR_EXPRESSION: i16 = 128;
pub const STREAMS_INVALID_TOPOLOGY: i16 = 130;

pub fn control_error_code(error: &ControlError) -> i16 {
    match error {
        ControlError::TopicNotFound(_) | ControlError::PartitionNotFound { .. } => {
            UNKNOWN_TOPIC_OR_PARTITION
        }
        ControlError::TopicAlreadyExists(_) => TOPIC_ALREADY_EXISTS,
        ControlError::InvalidTopic(_) => INVALID_TOPIC_EXCEPTION,
        ControlError::InvalidPartitionCount { .. } => INVALID_PARTITIONS,
        ControlError::OffsetOutOfRange { .. } => OFFSET_OUT_OF_RANGE,
        ControlError::GroupNotFound(_) | ControlError::GroupProtocolMismatch(_) => {
            COORDINATOR_NOT_AVAILABLE
        }
        ControlError::NonEmptyGroup(_) => NON_EMPTY_GROUP,
        ControlError::GroupMaxSizeReached(_) => GROUP_MAX_SIZE_REACHED,
        ControlError::GroupMemberNotFound { .. } => 25,
        ControlError::MemberIdRequired { .. } => MEMBER_ID_REQUIRED,
        ControlError::InconsistentGroupProtocol(_) => INCONSISTENT_GROUP_PROTOCOL,
        ControlError::RebalanceInProgress(_) => REBALANCE_IN_PROGRESS,
        ControlError::FencedInstanceId { .. } => FENCED_INSTANCE_ID,
        ControlError::FencedMemberEpoch { .. } => FENCED_MEMBER_EPOCH,
        ControlError::ShareSessionNotFound { .. } => SHARE_SESSION_NOT_FOUND,
        ControlError::InvalidShareSessionEpoch { .. } => INVALID_SHARE_SESSION_EPOCH,
        ControlError::InvalidShareRecordState(_) => INVALID_RECORD_STATE,
        ControlError::FencedShareLeaderEpoch { .. } => FENCED_LEADER_EPOCH,
        ControlError::FencedShareStateEpoch { .. } => FENCED_STATE_EPOCH,
        ControlError::UnsupportedConsumerAssignor(_) => UNSUPPORTED_ASSIGNOR,
        ControlError::UnsupportedVersion(_) => UNSUPPORTED_VERSION,
        ControlError::UnreleasedInstanceId { .. } => UNRELEASED_INSTANCE_ID,
        ControlError::IllegalGeneration { .. } => ILLEGAL_GENERATION,
        ControlError::InvalidRequest(_) => INVALID_REQUEST,
        ControlError::InvalidRegularExpression(_) => INVALID_REGULAR_EXPRESSION,
        ControlError::InvalidConfiguration(_) => INVALID_CONFIG,
        ControlError::InvalidUpdateVersion(_) => INVALID_UPDATE_VERSION,
        ControlError::ClientMetricSubscriptionNotFound(_) => RESOURCE_NOT_FOUND,
        ControlError::OutOfOrderSequence { .. } => OUT_OF_ORDER_SEQUENCE_NUMBER,
        ControlError::ProducerFenced { .. } => PRODUCER_FENCED,
        ControlError::TransactionCoordinatorFenced { .. } => TRANSACTION_COORDINATOR_FENCED,
        ControlError::UnknownProducer(_) => UNKNOWN_PRODUCER_ID,
        ControlError::InvalidTransactionState(_) => INVALID_TXN_STATE,
        ControlError::InvalidTransactionTimeout(_) => INVALID_TRANSACTION_TIMEOUT,
        ControlError::TransactionNotFound(_) => 105,
        ControlError::DelegationTokenNotFound => DELEGATION_TOKEN_NOT_FOUND,
        ControlError::DelegationTokenOwnerMismatch => DELEGATION_TOKEN_OWNER_MISMATCH,
        ControlError::DelegationTokenExpired => DELEGATION_TOKEN_EXPIRED,
        ControlError::Database(_) | ControlError::Migration(_) => UNKNOWN_SERVER_ERROR,
    }
}
